In [1]:
import numpy as np

Create a NP array of shape (4,4)
filled with random integers between 1
and 100. Replace all even numbers with
0.

In [5]:
import random

list = []
for i in range(16):
    list.append(random.randint(1, 100))
    
arr = np.array(list)
arr = arr.reshape(4, 4)    
print(arr)

[[95 89 99 38]
 [10 49 10  7]
 [27 36 23  4]
 [54 54 80 56]]


## Qn 2

In [6]:
list = []
for i in range(36):
    list.append(random.randint(1, 100))
    
arr = np.array(list)
arr = arr.reshape(6,6)    
print(arr)

[[13 47 37 31 26 95]
 [74 48 52 21 12 26]
 [67 64 30 92 33 98]
 [75 25 15 78 80 28]
 [89 29 31 98 72 73]
 [96 59 95 15 40 94]]


(a)The middle 2x2 sub-matrix

In [7]:
arr_middle = arr[2:4, 2:4]
print(arr_middle)

[[30 92]
 [15 78]]


(b) All even-indexed rows, 

In [9]:
arr_even_ind_row = arr[::2, ::]
print(arr_even_ind_row)

[[13 47 37 31 26 95]
 [67 64 30 92 33 98]
 [89 29 31 98 72 73]]


(c) The diagonal elements.

In [10]:
arr_diagonal = np.diag(arr)
print(arr_diagonal)

[13 48 30 78 72 94]


## Qn 3

Broadcasting

Create a 3x3 matrix of ones and add a 1D
array [1,2,3] to each row using
broadcasting. Use NumPy broadcasting with +

operation.

In [11]:
list = []
for i in range(9):
    list.append(random.randint(1, 100))
    
arr = np.array(list)
arr = arr.reshape(3, 3)    
print(arr)

[[ 46 100  27]
 [ 16  38  66]
 [ 39  44   5]]


In [12]:
arr_add  = [3, 4, 5]

arr = arr + arr_add
print(arr)

[[ 49 104  32]
 [ 19  42  71]
 [ 42  48  10]]


## Qn 4

Given an array of employee salaries, calculate the mean, median, and standard
deviation.

In [14]:
arr = np.array([5000, 4000, 3000, 3500, 4500])
print('Mean: ', np.mean(arr))
print('Median: ', np.median(arr))
print('Standard Deviation: ', np.std(arr))

Mean:  4000.0
Median:  4000.0
Standard Deviation:  707.1067811865476


## Qn 5


In [ ]:
marks = np.array([34, 35, 45, 38, 48])
indices = np.argsort(marks)[::-1] # storing index in sorted val of element
indices

array([4, 2, 3, 1, 0], dtype=int64)

## Qn 6

Convert a 1D array of length 16 into a
4x4 matrix and then flatten it back.

In [ ]:
list = []
for i in range(16):
    list.append(random.randint(1, 100))
    
arr = np.array(list)
arr = arr.reshape(4, 4)    
print(arr)

[[ 9 23 41 96]
 [27 60 17 99]
 [29 68 69 57]
 [61 85 11 83]]


In [17]:
print(arr.flatten(order="C")) # row wise
print(arr.flatten(order="F")) # column wise
print(arr.flatten(order="A")) # as stored in memory

[ 9 23 41 96 27 60 17 99 29 68 69 57 61 85 11 83]
[ 9 27 29 61 23 60 68 85 41 17 69 11 96 99 57 83]
[ 9 23 41 96 27 60 17 99 29 68 69 57 61 85 11 83]


## Qn 7

Given an array of temperatures in
Fahrenheit, convert them to Celsius using
a vectorized operation.

In [20]:
arr = np.array([32, 35, 36, 33,37, 38]) # temp in Cel
arr_fr = np.array([x * (9/5) + 32 for x in arr])
print(arr_fr)

[ 89.6  95.   96.8  91.4  98.6 100.4]


## Qn 8

A 10x10 matrix represents a grid where 1
means occupied and 0 means free. Find
how many positions are occupied.

In [ ]:
list = []
for i in range(100):
    list.append(random.randint(0, 1))
    
arr = np.array(list)
arr = arr.reshape(10, 10)   
print(arr)



[[1 1 1 0 0 1 1 0 0 1]
 [0 1 0 1 1 1 1 1 1 0]
 [0 1 1 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0 1 0 1]
 [1 1 0 0 0 1 1 1 0 1]
 [0 1 1 1 0 1 1 1 0 1]
 [0 1 1 1 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 1 1 0]
 [0 1 1 1 0 1 1 0 1 1]]


In [26]:
occupied = np.count_nonzero(arr)
empty = 100 - occupied
print('Occupied:', occupied)
print("Empty: ", empty)

Occupied: 56
Empty:  44
