In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [9]:
arr_org = np.array([[1.0, 0.0], 
                [0.0, 0.0]])

arr = np.tile(arr_org, (3, 4))
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Topic 1

In [10]:
arr = arr[::2, ::2]
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
arr = np.tile(arr_org, (3, 4))
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Topic 2

In [15]:
arr = arr[::, ::3]
print(arr)

[[1. 0. 1.]
 [0. 0. 0.]
 [1. 0. 1.]
 [0. 0. 0.]
 [1. 0. 1.]
 [0. 0. 0.]]


In [21]:
arr = np.tile(arr_org, (3, 4))
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Topic 3

In [22]:
arr = arr[2:4, 2:6]
print(arr)

[[1. 0. 1. 0.]
 [0. 0. 0. 0.]]


Topic 4

In [39]:
arr1 = np.arange(36)
arr1 =arr1.reshape(6, 6)
print(arr1)

print()
print('Diagonal: ')
print(arr1.diagonal())

print()
print('Daigonal 1')
print(np.diag(arr1, k = 1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Diagonal: 
[ 0  7 14 21 28 35]

Daigonal 1
[ 1  8 15 22 29]


Topic 5

In [34]:
arr1 = np.arange(36)
arr1 =arr1.reshape(6, 6)
print(arr1)

print()
print('Rev Col: ')
rev_col = print(arr1[::, ::-1])

print()
print('Rev Row: ')
rev_row = print(arr1[::-1, ::])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Rev Col: 
[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]
 [23 22 21 20 19 18]
 [29 28 27 26 25 24]
 [35 34 33 32 31 30]]

Rev Row: 
[[30 31 32 33 34 35]
 [24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]
